version: '3'

services:

  db:
    image: mariadb:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./etc/mysql/utf8.cnf:/etc/mysql/conf.d/utf8.cnf:ro
    restart: always

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
      - PMA_ARBITRARY=1
      ports:
      - 127.0.0.1:${WP_PORT_PHPMA}:80
      volumes:
      - /sessions
      restart: always

  httpd:
    labels:
      ch.epfl.jahia2wp.httpd.env: ${WP_ENV}
    image: epflidevelop/os-wp-httpd
    volumes:
      - ./volumes/srv:/srv
    links:
      - db:db
    environment:
      - WP_ENV=${WP_ENV}
    restart: always

  mgmt:
    labels:
      ch.epfl.jahia2wp.mgmt.env: ${WP_ENV}
    image: epflidevelop/os-wp-mgmt
    env_file:
      - .env
    environment:
      - WP_ENV=${WP_ENV}
      - LOGGING_FILE=/srv/${WP_ENV}/logs/jahia2wp.log
    volumes:
      - ./volumes/srv:/srv
      - ./etc/.bash_history:/var/www/.bash_history
      - ./etc/.aliases:/srv/.aliases
      - ./etc/.bashrc:/srv/.bashrc
      - ./data:/srv/${WP_ENV}/jahia2wp/data
      - ./requirements:/srv/${WP_ENV}/jahia2wp/requirements
      - ./src:/srv/${WP_ENV}/jahia2wp/src
      - ./functional_tests:/srv/${WP_ENV}/jahia2wp/functional_tests
      - ./Makefile.mgmt:/srv/${WP_ENV}/jahia2wp/Makefile
      - .env:/srv/${WP_ENV}/jahia2wp/.env
    restart: always
