- include_vars: update-vars.yml

- name: Zip file for the EPFL plug-in
  run_once: true
  local_action:
    module: archive
    dest: "{{ epfl_plugin_zip_file }}"
    format: zip
    path: "{{ epfl_plugin_dir }}"

- name: Install Zip file
  unarchive:
    src: "{{ epfl_plugin_zip_file }}"
    dest: "{{ wp_plugins_dir }}"
  when: "wp_can.write_code"
  register: _epfl_plugin_zip_file

- name: deactivate EPFL plug-in
  command: "{{ wp_cli_command }} plugin deactivate"
  when: _epfl_plugin_zip_file.changed and play_unload_reload_plugins
  failed_when: false

- name: reactivate EPFL plug-in
  command: "{{ wp_cli_command }} plugin activate"
  when: _epfl_plugin_zip_file.changed and play_unload_reload_plugins
